import numpy as np

table_head_traditional = np.array([
    ["Time, s"],
    ["Temperature, K"],
    ["Cell 1 CH4, Pa"],
    ["Cell 1 H2O, Pa"],
    ["Cell 1 CO, Pa"],
    ["Cell 1 CO2, Pa"],
    ["Cell 1 H2, Pa"],
    ["Cell 1 r1, mol/s"],
    ["Cell 1 r2, mol/s"],
    ["Cell 1 r3, mol/s"],
    ["Cell 2 CH4, Pa"],
    ["Cell 2 H2O, Pa"],
    ["Cell 2 CO, Pa"],
    ["Cell 2 CO2, Pa"],
    ["Cell 2 H2, Pa"],
    ["Cell 2 r1, mol/s"],
    ["Cell 2 r2, mol/s"],
    ["Cell 2 r3, mol/s"],
    ["CH4 productivity, mol/s"],
    ["H2O productivity, mol/s"],
    ["CO productivity, mol/s"],
    ["CO2 productivity, mol/s"],
    ["H2 productivity, mol/s"],
    ]).T.tolist()

table_head = np.array([
    ["Time, s"],
    ["Temperature, K"],
    ["Cell 1 CH4, Pa"],
    ["Cell 1 H2O, Pa"],
    ["Cell 1 CO, Pa"],
    ["Cell 1 CO2, Pa"],
    ["Cell 1 H2, Pa"],
    ["Cell 1 r1, mol/s"],
    ["Cell 1 r2, mol/s"],
    ["Cell 1 r3, mol/s"],
    ["Cell 2 CH4, Pa"],
    ["Cell 2 H2O, Pa"],
    ["Cell 2 CO, Pa"],
    ["Cell 2 CO2, Pa"],
    ["Cell 2 H2, Pa"],
    ["Cell 2 r1, mol/s"],
    ["Cell 2 r2, mol/s"],
    ["Cell 2 r3, mol/s"],
    ["Burning cell CH4, Pa"],
    ["Burning cell H2O, Pa"],
    ["Burning cell CO, Pa"],
    ["Burning cell CO2, Pa"],
    ["Burning cell H2, Pa"],
    ["Out cell 1 H2, Pa"],
    ["Out cell 2 H2, Pa"],
    ["Out cell 1 H2, mol"],
    ["Out cell 2 H2, mol"],
    ["Big out cell H2, mol"],
    ["H2 productivity, mol/s"],
    ["CH4 content, %"],
    ["H2O content, %"],
    ["CO content, %"],
    ["CO2 content, %"],
    ["H2 content, %"],
    ]).T.tolist()

if __name__ == "__main__":
    print(type(table_head))
